name: Angular Package Release

on:
  release:
    types: [created]

jobs:
  publish-angular-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          cache: yarn
      - run: yarn setup
      - run: yarn angular build
      - name: Create .npmrc
        run: |
          echo "@fp:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "registry=https://npm.pkg.github.com/" >> .npmrc
      - name: Publish to next tag
        run: yarn changeset publish --tag ${{ inputs.dist-tag }}
      - run: yarn angular publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
