name: Angular Package Release

on:
  release:
    types: [created]

jobs:
  publish-ui-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          cache: yarn
          scope: '@fitnesspassport'
      - name: Create .npmrc
        run: |
          echo 'before'
          cat .npmrc
          echo '/before'
          echo "@FitnessPassport:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "@fitnesspassport:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_NPM_TOKEN}" >> .npmrc
          echo "//registry.yarnpkg.com/:_authToken=${GITHUB_NPM_TOKEN}" >> .npmrc
          echo 'after'
          cat .npmrc
          echo '/after'
      - run: yarn ui install
      - run: yarn ui build
      - run: yarn ui publish --new-version $(cat ./packages/ui/package.json | jq -r '.version') || true
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish-angular-package:
    needs: publish-ui-package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          cache: yarn
          scope: '@fitnesspassport'
      - name: Create .npmrc
        run: |
          echo "@fitnesspassport:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
          echo "//registry.yarnpkg.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
      - run: yarn angular install
      - run: yarn angular build
      - run: yarn angular publish --new-version $(cat ./packages/angular/projects/ui-angular/package.json | jq -r '.version')
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
